server:
  port: 8080

spring:
  application:
    name: patient-reservation
    version: "@project.version@"
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://kubernetes.docker.internal:3306/patient_reservation
    username: rsvuser
    password: rsvpwd
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 900000
      connection-timeout: 10000
      idle-timeout: 600000
      minimum-idle: 5
      maximum-pool-size: 10
  liquibase:
    change-log: classpath:liquibase/master.xml
    contexts: ddl

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
info:
  tags:
    environment: ${spring.config.activate.on-profile}

logging:
  level:
    com.patient.reservation: INFO

application:
  security:
    basic:
      username: rsvuser
      password: rsvpwd
    jwt:
      jwtSecret: weakprivatesecret
      jwtExpiration: 60

---
#==============================================#
# LOCAL                                        #
#==============================================#

spring:
  config:
    activate:
      on-profile: local
  liquibase:
    contexts: ddl, data

logging:
  level:
    com.patient.reservation: DEBUG
    org.springframework.security: DEBUG